import { green, orange, red, blue, yellow, gray } from './colors.js'

export const semanticColors = {
  text: {
    neutral: {
      default: 'rgba(0, 0, 0, 0.9)',
      muted: 'rgba(0, 0, 0, 0.6)',
      quiet: 'rgba(0, 0, 0, 0.4)',
      disabled: 'rgba(0, 0, 0, 0.3)',
    },
    inverse: {
      default: 'rgba(255, 255, 255, 1)',
      muted: 'rgba(255, 255, 255, 0.8)',
      quiet: 'rgba(255, 255, 255, 0.6)',
    },
    brand: {
      default: 'var(--text-brand-default)',
      emphasis: 'var(--text-brand-emphasis)',
      muted: 'var(--text-brand-muted)',
    },
    accent: {
      default: orange[500],
      emphasis: orange[600],
    },
    success: {
      default: 'rgba(17, 146, 92, 1)',
      emphasis: green[700],
    },
    danger: {
      default: 'rgba(199, 26, 26, 1)',
      emphasis: 'rgba(153, 20, 20, 1)',
    },
    info: {
      default: 'rgba(26, 126, 199, 1)',
      emphasis: blue[600],
    },
    warning: {
      default: 'rgba(145, 129, 8, 1)',
      emphasis: 'rgba(106, 95, 6, 1)',
    },
  },
  bg: {
    surface: {
      l0: 'white',
      l1: gray[0],
      l2: gray[50],
      l3: gray[100],
    },
    overlay: {
      default: 'rgba(0, 0, 0, 0.4)',
    },
    disable: gray[50],
    brand: {
      bold: { rest: 'var(--bg-brand-bold-rest)' },
      emphasis: {
        rest: 'var(--bg-brand-emphasis-rest)',
        hover: 'var(--bg-brand-emphasis-hover)',
        active: 'var(--bg-brand-emphasis-active)',
      },
      muted: {
        rest: 'var(--bg-brand-muted-rest)',
        hover: 'var(--bg-brand-muted-hover)',
        active: 'var(--bg-brand-muted-active)',
      },
      subtle: {
        rest: 'var(--bg-brand-subtle-rest)',
        hover: 'var(--bg-brand-subtle-hover)',
        active: 'var(--bg-brand-subtle-active)',
      },
      quiet: {
        rest: 'var(--bg-brand-quiet-rest)',
        hover: 'var(--bg-brand-quiet-hover)',
        active: 'var(--bg-brand-quiet-active)',
      },
    },
    accent: {
      bold: { rest: orange[600] },
      emphasis: {
        rest: orange[400],
        hover: orange[500],
        active: orange[600],
      },
      muted: {
        rest: orange[50],
        hover: orange[100],
        active: orange[200],
      },
      subtle: {
        rest: orange[0],
        hover: orange[50],
        active: orange[100],
      },
      quiet: {
        rest: 'transparent',
        hover: orange[0],
        active: orange[50],
      },
    },
    neutral: {
      emphasis: {
        rest: gray[700],
        hover: gray[800],
        active: gray[900],
      },
      muted: {
        rest: gray[100],
        hover: gray[200],
        active: gray[300],
      },
      subtle: {
        rest: gray[50],
        hover: gray[100],
        active: gray[200],
      },
      quiet: {
        rest: 'transparent',
        hover: gray[0],
        active: gray[50],
      },
    },
    success: {
      bold: { rest: green[700] },
      emphasis: {
        rest: green[500],
        hover: green[600],
        active: green[700],
      },
      muted: {
        rest: green[50],
        hover: green[100],
        active: green[200],
      },
      subtle: {
        rest: green[0],
        hover: green[50],
        active: green[100],
      },
      quiet: {
        rest: 'transparent',
        hover: green[0],
        active: green[50],
      },
    },
    danger: {
      bold: { rest: red[600] },
      emphasis: {
        rest: red[500],
        hover: red[600],
        active: red[700],
      },
      muted: {
        rest: red[50],
        hover: red[100],
        active: red[200],
      },
      subtle: {
        rest: red[0],
        hover: red[50],
        active: red[100],
      },
      quiet: {
        rest: 'transparent',
        hover: red[0],
        active: red[50],
      },
    },
    info: {
      default: blue[600],
      strong: blue[900],
      bold: { rest: blue[600] },
      emphasis: {
        rest: blue[500],
        hover: blue[600],
        active: blue[700],
      },
      muted: {
        rest: blue[50],
        hover: blue[100],
        active: blue[200],
      },
      subtle: {
        rest: 'white',
        hover: blue[50],
        active: blue[100],
      },
      quiet: {
        rest: 'transparent',
        hover: blue[0],
        active: blue[50],
      },
    },
    warning: {
      bold: { rest: yellow[800] },
      emphasis: {
        rest: yellow[500],
        hover: yellow[600],
        active: yellow[700],
      },
      muted: {
        rest: yellow[200],
        hover: yellow[300],
        active: yellow[400],
      },
      subtle: {
        rest: 'white',
        hover: yellow[100],
        active: yellow[200],
      },
      quiet: {
        rest: 'transparent',
        hover: yellow[0],
        active: yellow[50],
      },
    },
  },
  border: {
    brand: {
      emphasis: 'var(--border-brand-emphasis)',
      muted: 'var(--border-brand-muted)',
      opacity: 'var(--border-brand-opacity)',
      quiet: 'var(--border-brand-quiet)',
    },
    accent: {
      emphasis: orange[600],
      muted: orange[200],
      opacity: 'rgba(235, 87, 4, 0.5)',
    },
    neutral: {
      emphasis: gray[700],
      muted: gray[100],
      opacity: 'rgba(115, 131, 140, 0.5)',
      quiet: gray[50],
      white: 'rgba(255, 255, 255, 0.5)',
    },
    success: {
      emphasis: green[700],
      muted: green[100],
      opacity: 'rgba(17, 146, 92, 0.5)',
    },
    danger: {
      emphasis: red[500],
      muted: red[100],
      opacity: 'rgba(199, 26, 26, 0.5)',
      quiet: red[50],
    },
    info: {
      emphasis: blue[500],
      muted: blue[200],
      opacity: 'rgba(26, 126, 199, 0.5)',
      quiet: blue[50],
    },
    warning: {
      emphasis: yellow[800],
      muted: yellow[500],
      opacity: 'rgba(145, 129, 8, 0.5)',
      quiet: yellow[300],
    },
  },
  divider: {
    emphasis: 'rgba(0, 0, 0, 0.2)',
    default: 'rgba(0, 0, 0, 0.1)',
    muted: 'rgba(0, 0, 0, 0.05)',
    quiet: 'rgba(0, 0, 0, 0.02)',
  },
}

export const semanticTextShortcut = {
  'text-neutral': 'text-[var(--text-neutral-default)]',
  'text-neutral-muted': 'text-[var(--text-neutral-muted)]',
  'text-neutral-quiet': 'text-[var(--text-neutral-quiet)]',
  'text-neutral-disabled': 'text-[var(--text-neutral-disabled)]',
  'text-inverse': 'text-[var(--text-inverse-default)]',
  'text-inverse-muted': 'text-[var(--text-inverse-muted)]',
  'text-inverse-quiet': 'text-[var(--text-inverse-quiet)]',
  'text-brand': 'text-[var(--text-brand-default)]',
  'text-brand-emphasis': 'text-[var(--text-brand-emphasis)]',
  'text-brand-muted': 'text-[var(--text-brand-muted)]',
  'text-accent': 'text-[var(--text-accent-default)]',
  'text-accent-emphasis': 'text-[var(--text-accent-emphasis)]',
  'text-success': 'text-[var(--text-success-default)]',
  'text-success-emphasis': 'text-[var(--text-success-emphasis)]',
  'text-danger': 'text-[var(--text-danger-default)]',
  'text-danger-emphasis': 'text-[var(--text-danger-emphasis)]',
  'text-info': 'text-[var(--text-info-default)]',
  'text-info-emphasis': 'text-[var(--text-info-emphasis)]',
  'text-warning': 'text-[var(--text-warning-default)]',
  'text-warning-emphasis': 'text-[var(--text-warning-emphasis)]',
}

export const semanticBgShortcut = {
  'bg-surface-l0': 'bg-[var(--bg-surface-l0)]',
  'bg-surface-l1': 'bg-[var(--bg-surface-l1)]',
  'bg-surface-l2': 'bg-[var(--bg-surface-l2)]',
  'bg-surface-l3': 'bg-[var(--bg-surface-l3)]',
  'bg-overlay': 'bg-[var(--bg-overlay-default)]',
  'bg-disable': 'bg-[var(--bg-disable)]',
  'bg-info-default': 'bg-[var(--bg-info-default)]',
  'bg-info-strong': 'bg-[var(--bg-info-strong)]',
  'bg-brand-emphasis-rest': 'bg-[var(--bg-brand-emphasis-rest)]',
  'bg-brand-emphasis-hover': 'bg-[var(--bg-brand-emphasis-hover)]',
  'bg-brand-emphasis-active': 'bg-[var(--bg-brand-emphasis-active)]',
  'bg-brand-muted-rest': 'bg-[var(--bg-brand-muted-rest)]',
  'bg-brand-muted-hover': 'bg-[var(--bg-brand-muted-hover)]',
  'bg-brand-muted-active': 'bg-[var(--bg-brand-muted-active)]',
  'bg-brand-quiet-rest': 'bg-[var(--bg-brand-quiet-rest)]',
  'bg-brand-quiet-hover': 'bg-[var(--bg-brand-quiet-hover)]',
  'bg-brand-quiet-active': 'bg-[var(--bg-brand-quiet-active)]',
  'bg-brand-bold-rest': 'bg-[var(--bg-brand-bold-rest)]',
  'bg-brand-subtle-rest': 'bg-[var(--bg-brand-subtle-rest)]',
  'bg-brand-subtle-hover': 'bg-[var(--bg-brand-subtle-hover)]',
  'bg-brand-subtle-active': 'bg-[var(--bg-brand-subtle-active)]',
  'bg-accent-emphasis-rest': 'bg-[var(--bg-accent-emphasis-rest)]',
  'bg-accent-emphasis-hover': 'bg-[var(--bg-accent-emphasis-hover)]',
  'bg-accent-emphasis-active': 'bg-[var(--bg-accent-emphasis-active)]',
  'bg-accent-muted-rest': 'bg-[var(--bg-accent-muted-rest)]',
  'bg-accent-muted-hover': 'bg-[var(--bg-accent-muted-hover)]',
  'bg-accent-muted-active': 'bg-[var(--bg-accent-muted-active)]',
  'bg-accent-quiet-rest': 'bg-[var(--bg-accent-quiet-rest)]',
  'bg-accent-quiet-hover': 'bg-[var(--bg-accent-quiet-hover)]',
  'bg-accent-quiet-active': 'bg-[var(--bg-accent-quiet-active)]',
  'bg-accent-bold-rest': 'bg-[var(--bg-accent-bold-rest)]',
  'bg-accent-subtle-rest': 'bg-[var(--bg-accent-subtle-rest)]',
  'bg-accent-subtle-hover': 'bg-[var(--bg-accent-subtle-hover)]',
  'bg-accent-subtle-active': 'bg-[var(--bg-accent-subtle-active)]',
  'bg-neutral-emphasis-rest': 'bg-[var(--bg-neutral-emphasis-rest)]',
  'bg-neutral-emphasis-hover': 'bg-[var(--bg-neutral-emphasis-hover)]',
  'bg-neutral-emphasis-active': 'bg-[var(--bg-neutral-emphasis-active)]',
  'bg-neutral-muted-rest': 'bg-[var(--bg-neutral-muted-rest)]',
  'bg-neutral-muted-hover': 'bg-[var(--bg-neutral-muted-hover)]',
  'bg-neutral-muted-active': 'bg-[var(--bg-neutral-muted-active)]',
  'bg-neutral-quiet-rest': 'bg-[var(--bg-neutral-quiet-rest)]',
  'bg-neutral-quiet-hover': 'bg-[var(--bg-neutral-quiet-hover)]',
  'bg-neutral-quiet-active': 'bg-[var(--bg-neutral-quiet-active)]',
  'bg-neutral-subtle-rest': 'bg-[var(--bg-neutral-subtle-rest)]',
  'bg-neutral-subtle-hover': 'bg-[var(--bg-neutral-subtle-hover)]',
  'bg-neutral-subtle-active': 'bg-[var(--bg-neutral-subtle-active)]',
  'bg-success-emphasis-rest': 'bg-[var(--bg-success-emphasis-rest)]',
  'bg-success-emphasis-hover': 'bg-[var(--bg-success-emphasis-hover)]',
  'bg-success-emphasis-active': 'bg-[var(--bg-success-emphasis-active)]',
  'bg-success-muted-rest': 'bg-[var(--bg-success-muted-rest)]',
  'bg-success-muted-hover': 'bg-[var(--bg-success-muted-hover)]',
  'bg-success-muted-active': 'bg-[var(--bg-success-muted-active)]',
  'bg-success-quiet-rest': 'bg-[var(--bg-success-quiet-rest)]',
  'bg-success-quiet-hover': 'bg-[var(--bg-success-quiet-hover)]',
  'bg-success-quiet-active': 'bg-[var(--bg-success-quiet-active)]',
  'bg-success-bold-rest': 'bg-[var(--bg-success-bold-rest)]',
  'bg-success-subtle-rest': 'bg-[var(--bg-success-subtle-rest)]',
  'bg-success-subtle-hover': 'bg-[var(--bg-success-subtle-hover)]',
  'bg-success-subtle-active': 'bg-[var(--bg-success-subtle-active)]',
  'bg-danger-emphasis-rest': 'bg-[var(--bg-danger-emphasis-rest)]',
  'bg-danger-emphasis-hover': 'bg-[var(--bg-danger-emphasis-hover)]',
  'bg-danger-emphasis-active': 'bg-[var(--bg-danger-emphasis-active)]',
  'bg-danger-muted-rest': 'bg-[var(--bg-danger-muted-rest)]',
  'bg-danger-muted-hover': 'bg-[var(--bg-danger-muted-hover)]',
  'bg-danger-muted-active': 'bg-[var(--bg-danger-muted-active)]',
  'bg-danger-quiet-rest': 'bg-[var(--bg-danger-quiet-rest)]',
  'bg-danger-quiet-hover': 'bg-[var(--bg-danger-quiet-hover)]',
  'bg-danger-quiet-active': 'bg-[var(--bg-danger-quiet-active)]',
  'bg-danger-bold-rest': 'bg-[var(--bg-danger-bold-rest)]',
  'bg-danger-subtle-rest': 'bg-[var(--bg-danger-subtle-rest)]',
  'bg-danger-subtle-hover': 'bg-[var(--bg-danger-subtle-hover)]',
  'bg-danger-subtle-active': 'bg-[var(--bg-danger-subtle-active)]',
  'bg-info-emphasis-rest': 'bg-[var(--bg-info-emphasis-rest)]',
  'bg-info-emphasis-hover': 'bg-[var(--bg-info-emphasis-hover)]',
  'bg-info-emphasis-active': 'bg-[var(--bg-info-emphasis-active)]',
  'bg-info-muted-rest': 'bg-[var(--bg-info-muted-rest)]',
  'bg-info-muted-hover': 'bg-[var(--bg-info-muted-hover)]',
  'bg-info-muted-active': 'bg-[var(--bg-info-muted-active)]',
  'bg-info-quiet-rest': 'bg-[var(--bg-info-quiet-rest)]',
  'bg-info-quiet-hover': 'bg-[var(--bg-info-quiet-hover)]',
  'bg-info-quiet-active': 'bg-[var(--bg-info-quiet-active)]',
  'bg-info-bold-rest': 'bg-[var(--bg-info-bold-rest)]',
  'bg-info-subtle-rest': 'bg-[var(--bg-info-subtle-rest)]',
  'bg-info-subtle-hover': 'bg-[var(--bg-info-subtle-hover)]',
  'bg-info-subtle-active': 'bg-[var(--bg-info-subtle-active)]',
  'bg-warning-emphasis-rest': 'bg-[var(--bg-warning-emphasis-rest)]',
  'bg-warning-emphasis-hover': 'bg-[var(--bg-warning-emphasis-hover)]',
  'bg-warning-emphasis-active': 'bg-[var(--bg-warning-emphasis-active)]',
  'bg-warning-bold-rest': 'bg-[var(--bg-warning-bold-rest)]',
  'bg-warning-subtle-rest': 'bg-[var(--bg-warning-subtle-rest)]',
  'bg-warning-subtle-hover': 'bg-[var(--bg-warning-subtle-hover)]',
  'bg-warning-subtle-active': 'bg-[var(--bg-warning-subtle-active)]',
  'bg-warning-muted-rest': 'bg-[var(--bg-warning-muted-rest)]',
  'bg-warning-muted-hover': 'bg-[var(--bg-warning-muted-hover)]',
  'bg-warning-muted-active': 'bg-[var(--bg-warning-muted-active)]',
  'bg-warning-quiet-rest': 'bg-[var(--bg-warning-quiet-rest)]',
  'bg-warning-quiet-hover': 'bg-[var(--bg-warning-quiet-hover)]',
  'bg-warning-quiet-active': 'bg-[var(--bg-warning-quiet-active)]',
}

export const semanticBorderShortcut = {
  'border-brand-emphasis': 'border-[var(--border-brand-emphasis)]',
  'border-brand-muted': 'border-[var(--border-brand-muted)]',
  'border-accent-emphasis': 'border-[var(--border-accent-emphasis)]',
  'border-accent-muted': 'border-[var(--border-accent-muted)]',
  'border-neutral-emphasis': 'border-[var(--border-neutral-emphasis)]',
  'border-neutral-muted': 'border-[var(--border-neutral-muted)]',
  'border-neutral-quiet': 'border-[var(--border-neutral-quiet)]',
  'border-neutral-white': 'border-[var(--border-neutral-white)]',
  'border-success-emphasis': 'border-[var(--border-success-emphasis)]',
  'border-success-muted': 'border-[var(--border-success-muted)]',
  'border-danger-emphasis': 'border-[var(--border-danger-emphasis)]',
  'border-danger-muted': 'border-[var(--border-danger-muted)]',
  'border-info-emphasis': 'border-[var(--border-info-emphasis)]',
  'border-info-muted': 'border-[var(--border-info-muted)]',
  'border-warning-emphasis': 'border-[var(--border-warning-emphasis)]',
  'border-warning-muted': 'border-[var(--border-warning-muted)]',
  'border-brand-opacity': 'border-[var(--border-brand-opacity)]',
  'border-brand-quiet': 'border-[var(--border-brand-quiet)]',
  'border-accent-opacity': 'border-[var(--border-accent-opacity)]',
  'border-neutral-opacity': 'border-[var(--border-neutral-opacity)]',
  'border-success-opacity': 'border-[var(--border-success-opacity)]',
  'border-danger-opacity': 'border-[var(--border-danger-opacity)]',
  'border-danger-quiet': 'border-[var(--border-danger-quiet)]',
  'border-info-opacity': 'border-[var(--border-info-opacity)]',
  'border-info-quiet': 'border-[var(--border-info-quiet)]',
  'border-warning-opacity': 'border-[var(--border-warning-opacity)]',
  'border-warning-quiet': 'border-[var(--border-warning-quiet)]',
}

export const semanticShortcuts = [
  semanticTextShortcut,
  semanticBgShortcut,
  semanticBorderShortcut,
  {
    'divider-emphasis': 'border-[color:var(--divider-emphasis)]',
    'divider-default': 'border-[color:var(--divider-default)]',
    'divider-muted': 'border-[color:var(--divider-muted)]',
    'divider-quiet': 'border-[color:var(--divider-quiet)]',
  },
]
